# Generated by Django 3.1.5 on 2021-04-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('hash', models.CharField(max_length=64)),
                ('previoushash', models.CharField(max_length=64)),
                ('data', models.CharField(max_length=100)),
                ('nonce', models.CharField(max_length=15)),
            ],
        ),
    ]
