# Generated by Django 3.1.7 on 2021-04-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='previoushash',
            new_name='previous_hash',
        ),
    ]
